export const ErrorCodes = {
  Account: {
    NotCreated: 'AccountNotCreated',
    DiscordUserNotFound: 'DiscordUserNotFound',
  },
  Card: {
    NoCard: 'NoCard',
    NoCards: 'NoCards',
    NoCardsByRarety: 'NoCardsByRarety',
    NoCardsBySeason: 'NoCardsBySeason',
    NoCardsByPackId: 'NoCardsByPackId',
    InsufficientCards: 'InsufficientCards',
    NoAddCardToUserCollection: 'NoAddCardToUserCollection',
    NoCoinsToBuy: 'NoCoinsToBuy',
    NoCoinsToGive: 'NoCoinsToGive',
    NoCreateCard: 'NoCreateCard',
    RandomCardsNotFound: 'RandomCardsNotFound',
    NoCardsBySeasonAndUserId: 'NoCardsBySeasonAndUserId',
  },
  Common: {
    ConfigNotFound: 'ConfigNotFound',
    InvalidInput: 'InvalidInput',
    Unknown: 'Unknown',
  },
  Pack: {
    NoCreatePack: 'NoCreatePack',
    NoCreatePackCards: 'NoCreatePackCards',
    NoDeletePack: 'NoDeletePack',
  },
  Season: {
    NoSeason: 'NoSeason',
    NoSeasons: 'NoSeasons',
    NoCardsBySeason: 'NoCardsBySeason',
  },
  Subscription: {
    UserAlreadyHasSubscription: 'UserAlreadyHasSubscription',
  },
  User: {
    NoGems: 'NoGems',
    NoCoins: 'NoCoins',
    NoIncreaseCoins: 'NoIncreaseCoins',
    NoIncreaseGems: 'NoIncreaseGems',
    NoUserCard: 'NoUserCard',
    NoUserCards: 'NoUserCards',
    NoDecreaseCoins: 'NoDecreaseCoins',
    NoDecreaseGems: 'NoDecreaseGems',
    NoGiveCoins: 'NoGiveCoins',
    NoSetCoins: 'NoSetCoins',
    UnAuthorized: 'UnAuthorized',
    NoUpdateUserGems: 'NoUpdateUserGems',
    SenderNotFound: 'SenderNotFound',
    ReceiverNotFound: 'ReceiverNotFound',
    NoUser: 'NoUser',
    NoUserCreated: 'NoUserCreated',
    NoUserPack: 'NoUserPack',
    NoUserPacks: 'NoUserPacks',
    AlreadyExists: 'UserAlreadyExists',
    GiveCoinsRecipientEqualsSender: 'GiveCoinsRecipientEqualsSender',
    GiveCardRecipientEqualsSender: 'GiveCardRecipientEqualsSender',
  },
  System: {
    InvalidInput: 'InvalidInput',
    DatabaseError: 'DatabaseError',
    UnexpectedError: 'UnexpectedError',
  },
} as const;
